//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Prop
{
   
public partial class PropConfig
{
    private readonly Dictionary<int, Prop.PropConfigRecord> _dataMap;
    private readonly List<Prop.PropConfigRecord> _dataList;
    
    public PropConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Prop.PropConfigRecord>();
        _dataList = new List<Prop.PropConfigRecord>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Prop.PropConfigRecord _v;
            _v = Prop.PropConfigRecord.DeserializePropConfigRecord(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Prop.PropConfigRecord> DataMap => _dataMap;
    public List<Prop.PropConfigRecord> DataList => _dataList;

    public Prop.PropConfigRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Prop.PropConfigRecord Get(int key) => _dataMap[key];
    public Prop.PropConfigRecord this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}