//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Prop
{
public sealed partial class RandomPropConfigRecord :  Bright.Config.BeanBase 
{
    public RandomPropConfigRecord(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);PropPool = new System.Collections.Generic.List<Prop.PropPoolBean>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Prop.PropPoolBean _e0;  _e0 = Prop.PropPoolBean.DeserializePropPoolBean(_buf); PropPool.Add(_e0);}}
        PostInit();
    }

    public static RandomPropConfigRecord DeserializeRandomPropConfigRecord(ByteBuf _buf)
    {
        return new Prop.RandomPropConfigRecord(_buf);
    }

    /// <summary>
    /// 随机属性id
    /// </summary>
    public int Id { get; private set; }
    public System.Collections.Generic.List<Prop.PropPoolBean> PropPool { get; private set; }

    public const int __ID__ = -838305020;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in PropPool) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in PropPool) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "PropPool:" + Bright.Common.StringUtil.CollectionToString(PropPool) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}