//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Prop
{
   
public partial class RandomPropConfig
{
    private readonly Dictionary<int, Prop.RandomPropConfigRecord> _dataMap;
    private readonly List<Prop.RandomPropConfigRecord> _dataList;
    
    public RandomPropConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Prop.RandomPropConfigRecord>();
        _dataList = new List<Prop.RandomPropConfigRecord>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Prop.RandomPropConfigRecord _v;
            _v = Prop.RandomPropConfigRecord.DeserializeRandomPropConfigRecord(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Prop.RandomPropConfigRecord> DataMap => _dataMap;
    public List<Prop.RandomPropConfigRecord> DataList => _dataList;

    public Prop.RandomPropConfigRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Prop.RandomPropConfigRecord Get(int key) => _dataMap[key];
    public Prop.RandomPropConfigRecord this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}