//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Task
{
   
public partial class TaskConfig
{
    private readonly Dictionary<int, Task.TaskConfigRecord> _dataMap;
    private readonly List<Task.TaskConfigRecord> _dataList;
    
    public TaskConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Task.TaskConfigRecord>();
        _dataList = new List<Task.TaskConfigRecord>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Task.TaskConfigRecord _v;
            _v = Task.TaskConfigRecord.DeserializeTaskConfigRecord(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Task.TaskConfigRecord> DataMap => _dataMap;
    public List<Task.TaskConfigRecord> DataList => _dataList;

    public Task.TaskConfigRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Task.TaskConfigRecord Get(int key) => _dataMap[key];
    public Task.TaskConfigRecord this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}