//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.Conf.Task
{
public sealed partial class TaskFinishConditionBean :  Bright.Config.BeanBase 
{
    public TaskFinishConditionBean(ByteBuf _buf) 
    {
        KeyString = _buf.ReadString();
        ValueInt = _buf.ReadInt();
        PostInit();
    }

    public static TaskFinishConditionBean DeserializeTaskFinishConditionBean(ByteBuf _buf)
    {
        return new Task.TaskFinishConditionBean(_buf);
    }

    /// <summary>
    /// 条件Key
    /// </summary>
    public string KeyString { get; private set; }
    /// <summary>
    /// 条件Value
    /// </summary>
    public int ValueInt { get; private set; }

    public const int __ID__ = -1895728534;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "KeyString:" + KeyString + ","
        + "ValueInt:" + ValueInt + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}