//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Task
{
public sealed partial class TaskConfigRecord :  Bright.Config.BeanBase 
{
    public TaskConfigRecord(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        TaskName = _buf.ReadString();
        TaskDes = _buf.ReadString();
        TaskType = _buf.ReadString();
        TaskFinishType = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);TaskFinishCondition = new System.Collections.Generic.List<Task.TaskFinishConditionBean>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Task.TaskFinishConditionBean _e0;  _e0 = Task.TaskFinishConditionBean.DeserializeTaskFinishConditionBean(_buf); TaskFinishCondition.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);TaskPrize = new System.Collections.Generic.List<Item.ItemInfoBean>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Item.ItemInfoBean _e0;  _e0 = Item.ItemInfoBean.DeserializeItemInfoBean(_buf); TaskPrize.Add(_e0);}}
        PostInit();
    }

    public static TaskConfigRecord DeserializeTaskConfigRecord(ByteBuf _buf)
    {
        return new Task.TaskConfigRecord(_buf);
    }

    /// <summary>
    /// 任务id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 任务名称
    /// </summary>
    public string TaskName { get; private set; }
    /// <summary>
    /// 任务描述
    /// </summary>
    public string TaskDes { get; private set; }
    /// <summary>
    /// 任务类型
    /// </summary>
    public string TaskType { get; private set; }
    /// <summary>
    /// 任务完成类型
    /// </summary>
    public string TaskFinishType { get; private set; }
    public System.Collections.Generic.List<Task.TaskFinishConditionBean> TaskFinishCondition { get; private set; }
    public System.Collections.Generic.List<Item.ItemInfoBean> TaskPrize { get; private set; }

    public const int __ID__ = 1007987105;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in TaskFinishCondition) { _e?.Resolve(_tables); }
        foreach(var _e in TaskPrize) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in TaskFinishCondition) { _e?.TranslateText(translator); }
        foreach(var _e in TaskPrize) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "TaskName:" + TaskName + ","
        + "TaskDes:" + TaskDes + ","
        + "TaskType:" + TaskType + ","
        + "TaskFinishType:" + TaskFinishType + ","
        + "TaskFinishCondition:" + Bright.Common.StringUtil.CollectionToString(TaskFinishCondition) + ","
        + "TaskPrize:" + Bright.Common.StringUtil.CollectionToString(TaskPrize) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}