//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Hero
{
public sealed partial class HeroConfigRecord :  Bright.Config.BeanBase 
{
    public HeroConfigRecord(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        IsValid = _buf.ReadBool();
        HeroName = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);TalentInfo = new System.Collections.Generic.List<Hero.HeroTalentInfoBean>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Hero.HeroTalentInfoBean _e0;  _e0 = Hero.HeroTalentInfoBean.DeserializeHeroTalentInfoBean(_buf); TalentInfo.Add(_e0);}}
        PostInit();
    }

    public static HeroConfigRecord DeserializeHeroConfigRecord(ByteBuf _buf)
    {
        return new Hero.HeroConfigRecord(_buf);
    }

    /// <summary>
    /// 英雄Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 是否启用
    /// </summary>
    public bool IsValid { get; private set; }
    /// <summary>
    /// 英雄名字
    /// </summary>
    public string HeroName { get; private set; }
    public System.Collections.Generic.List<Hero.HeroTalentInfoBean> TalentInfo { get; private set; }

    public const int __ID__ = 886258369;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in TalentInfo) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in TalentInfo) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "IsValid:" + IsValid + ","
        + "HeroName:" + HeroName + ","
        + "TalentInfo:" + Bright.Common.StringUtil.CollectionToString(TalentInfo) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}