//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Hero
{
public sealed partial class HeroTalentInfoBean :  Bright.Config.BeanBase 
{
    public HeroTalentInfoBean(ByteBuf _buf) 
    {
        TalentLevel = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);TalentGroup = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TalentGroup.Add(_e0);}}
        PostInit();
    }

    public static HeroTalentInfoBean DeserializeHeroTalentInfoBean(ByteBuf _buf)
    {
        return new Hero.HeroTalentInfoBean(_buf);
    }

    /// <summary>
    /// 天赋等级
    /// </summary>
    public int TalentLevel { get; private set; }
    /// <summary>
    /// 天赋组
    /// </summary>
    public System.Collections.Generic.List<int> TalentGroup { get; private set; }

    public const int __ID__ = 609663896;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "TalentLevel:" + TalentLevel + ","
        + "TalentGroup:" + Bright.Common.StringUtil.CollectionToString(TalentGroup) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}