//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Hero
{
public sealed partial class HeroTalentConfigRecord :  Bright.Config.BeanBase 
{
    public HeroTalentConfigRecord(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        TalentName = _buf.ReadString();
        NeedTalentPoint = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);TalentBuffs = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TalentBuffs.Add(_e0);}}
        PostInit();
    }

    public static HeroTalentConfigRecord DeserializeHeroTalentConfigRecord(ByteBuf _buf)
    {
        return new Hero.HeroTalentConfigRecord(_buf);
    }

    /// <summary>
    /// 天赋Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 天赋名称
    /// </summary>
    public string TalentName { get; private set; }
    /// <summary>
    /// 消耗天赋点
    /// </summary>
    public int NeedTalentPoint { get; private set; }
    /// <summary>
    /// 天赋Buff
    /// </summary>
    public System.Collections.Generic.List<int> TalentBuffs { get; private set; }

    public const int __ID__ = 1387207501;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "TalentName:" + TalentName + ","
        + "NeedTalentPoint:" + NeedTalentPoint + ","
        + "TalentBuffs:" + Bright.Common.StringUtil.CollectionToString(TalentBuffs) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}