//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Season
{
   
public partial class SeasonConfig
{
    private readonly Dictionary<int, Season.SeasonConfigRecord> _dataMap;
    private readonly List<Season.SeasonConfigRecord> _dataList;
    
    public SeasonConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Season.SeasonConfigRecord>();
        _dataList = new List<Season.SeasonConfigRecord>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Season.SeasonConfigRecord _v;
            _v = Season.SeasonConfigRecord.DeserializeSeasonConfigRecord(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Season.SeasonConfigRecord> DataMap => _dataMap;
    public List<Season.SeasonConfigRecord> DataList => _dataList;

    public Season.SeasonConfigRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Season.SeasonConfigRecord Get(int key) => _dataMap[key];
    public Season.SeasonConfigRecord this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}