//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Season
{
public sealed partial class SeasonConfigRecord :  Bright.Config.BeanBase 
{
    public SeasonConfigRecord(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        SeasonName = _buf.ReadString();
        SeasonStartTime = _buf.ReadLong();
        SeasonEndTime = _buf.ReadLong();
        PostInit();
    }

    public static SeasonConfigRecord DeserializeSeasonConfigRecord(ByteBuf _buf)
    {
        return new Season.SeasonConfigRecord(_buf);
    }

    /// <summary>
    /// 赛季id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 赛季名称
    /// </summary>
    public string SeasonName { get; private set; }
    /// <summary>
    /// 赛季开始时间
    /// </summary>
    public long SeasonStartTime { get; private set; }
    public long SeasonStartTime_Millis => SeasonStartTime * 1000L;
    /// <summary>
    /// 赛季结束时间
    /// </summary>
    public long SeasonEndTime { get; private set; }
    public long SeasonEndTime_Millis => SeasonEndTime * 1000L;

    public const int __ID__ = -1470136927;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "SeasonName:" + SeasonName + ","
        + "SeasonStartTime:" + SeasonStartTime + ","
        + "SeasonEndTime:" + SeasonEndTime + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}