//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.Conf.Dota
{
   
public partial class BattlePassTaskConfig
{
    private readonly Dictionary<int, Dota.BattlePassTaskConfigRecord> _dataMap;
    private readonly List<Dota.BattlePassTaskConfigRecord> _dataList;
    
    public BattlePassTaskConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Dota.BattlePassTaskConfigRecord>();
        _dataList = new List<Dota.BattlePassTaskConfigRecord>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Dota.BattlePassTaskConfigRecord _v;
            _v = Dota.BattlePassTaskConfigRecord.DeserializeBattlePassTaskConfigRecord(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Dota.BattlePassTaskConfigRecord> DataMap => _dataMap;
    public List<Dota.BattlePassTaskConfigRecord> DataList => _dataList;

    public Dota.BattlePassTaskConfigRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Dota.BattlePassTaskConfigRecord Get(int key) => _dataMap[key];
    public Dota.BattlePassTaskConfigRecord this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}