//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.Conf.Dota
{
public sealed partial class BattlePassLevelUpConfigRecord :  Bright.Config.BeanBase 
{
    public BattlePassLevelUpConfigRecord(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        BattlePassLevel = _buf.ReadInt();
        SeasonId = _buf.ReadInt();
        LevelUpExp = _buf.ReadInt();
        TaskComPrize = Item.ItemInfoBean.DeserializeItemInfoBean(_buf);
        TaskSpePrize = Item.ItemInfoBean.DeserializeItemInfoBean(_buf);
        PostInit();
    }

    public static BattlePassLevelUpConfigRecord DeserializeBattlePassLevelUpConfigRecord(ByteBuf _buf)
    {
        return new Dota.BattlePassLevelUpConfigRecord(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// BattlePass等级
    /// </summary>
    public int BattlePassLevel { get; private set; }
    /// <summary>
    /// 赛季ID
    /// </summary>
    public int SeasonId { get; private set; }
    /// <summary>
    /// 升级所需经验
    /// </summary>
    public int LevelUpExp { get; private set; }
    public Item.ItemInfoBean TaskComPrize { get; private set; }
    public Item.ItemInfoBean TaskSpePrize { get; private set; }

    public const int __ID__ = 1867395635;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        TaskComPrize?.Resolve(_tables);
        TaskSpePrize?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        TaskComPrize?.TranslateText(translator);
        TaskSpePrize?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "BattlePassLevel:" + BattlePassLevel + ","
        + "SeasonId:" + SeasonId + ","
        + "LevelUpExp:" + LevelUpExp + ","
        + "TaskComPrize:" + TaskComPrize + ","
        + "TaskSpePrize:" + TaskSpePrize + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}