//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Dota
{
public sealed partial class BattlePassChargeConfigRecord :  Bright.Config.BeanBase 
{
    public BattlePassChargeConfigRecord(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        SeasonId = _buf.ReadInt();
        IsCourier = _buf.ReadBool();
        ChargeTo = Item.ItemInfoBean.DeserializeItemInfoBean(_buf);
        ChargeBy = Item.ItemInfoBean.DeserializeItemInfoBean(_buf);
        PostInit();
    }

    public static BattlePassChargeConfigRecord DeserializeBattlePassChargeConfigRecord(ByteBuf _buf)
    {
        return new Dota.BattlePassChargeConfigRecord(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 赛季ID
    /// </summary>
    public int SeasonId { get; private set; }
    /// <summary>
    /// 是否是信使
    /// </summary>
    public bool IsCourier { get; private set; }
    public Item.ItemInfoBean ChargeTo { get; private set; }
    public Item.ItemInfoBean ChargeBy { get; private set; }

    public const int __ID__ = -1025100346;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        ChargeTo?.Resolve(_tables);
        ChargeBy?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        ChargeTo?.TranslateText(translator);
        ChargeBy?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "SeasonId:" + SeasonId + ","
        + "IsCourier:" + IsCourier + ","
        + "ChargeTo:" + ChargeTo + ","
        + "ChargeBy:" + ChargeBy + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}