//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.Conf.Dota
{
   
public partial class BuildingLevelUpConfig
{
    private readonly Dictionary<string, Dota.BuildingLevelUpConfigRecord> _dataMap;
    private readonly List<Dota.BuildingLevelUpConfigRecord> _dataList;
    
    public BuildingLevelUpConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<string, Dota.BuildingLevelUpConfigRecord>();
        _dataList = new List<Dota.BuildingLevelUpConfigRecord>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Dota.BuildingLevelUpConfigRecord _v;
            _v = Dota.BuildingLevelUpConfigRecord.DeserializeBuildingLevelUpConfigRecord(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<string, Dota.BuildingLevelUpConfigRecord> DataMap => _dataMap;
    public List<Dota.BuildingLevelUpConfigRecord> DataList => _dataList;

    public Dota.BuildingLevelUpConfigRecord GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Dota.BuildingLevelUpConfigRecord Get(string key) => _dataMap[key];
    public Dota.BuildingLevelUpConfigRecord this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}