//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.Conf.Dota
{
public sealed partial class BuildingLevelUpExpConfigRecord :  Bright.Config.BeanBase 
{
    public BuildingLevelUpExpConfigRecord(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Exp = _buf.ReadInt();
        TotalTalentPoint = _buf.ReadInt();
        PostInit();
    }

    public static BuildingLevelUpExpConfigRecord DeserializeBuildingLevelUpExpConfigRecord(ByteBuf _buf)
    {
        return new Dota.BuildingLevelUpExpConfigRecord(_buf);
    }

    /// <summary>
    /// 等级
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 所需经验
    /// </summary>
    public int Exp { get; private set; }
    /// <summary>
    /// 天赋总点数
    /// </summary>
    public int TotalTalentPoint { get; private set; }

    public const int __ID__ = 78790139;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Exp:" + Exp + ","
        + "TotalTalentPoint:" + TotalTalentPoint + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}