//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.Conf.Dota
{
   
public partial class BuildingLevelUpExpConfig
{
    private readonly Dictionary<int, Dota.BuildingLevelUpExpConfigRecord> _dataMap;
    private readonly List<Dota.BuildingLevelUpExpConfigRecord> _dataList;
    
    public BuildingLevelUpExpConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Dota.BuildingLevelUpExpConfigRecord>();
        _dataList = new List<Dota.BuildingLevelUpExpConfigRecord>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Dota.BuildingLevelUpExpConfigRecord _v;
            _v = Dota.BuildingLevelUpExpConfigRecord.DeserializeBuildingLevelUpExpConfigRecord(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Dota.BuildingLevelUpExpConfigRecord> DataMap => _dataMap;
    public List<Dota.BuildingLevelUpExpConfigRecord> DataList => _dataList;

    public Dota.BuildingLevelUpExpConfigRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Dota.BuildingLevelUpExpConfigRecord Get(int key) => _dataMap[key];
    public Dota.BuildingLevelUpExpConfigRecord this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}