//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Dota
{
public sealed partial class InfoPassLevelUpConfigRecord :  Bright.Config.BeanBase 
{
    public InfoPassLevelUpConfigRecord(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        TaskComPrize = Item.ItemInfoBean.DeserializeItemInfoBean(_buf);
        PostInit();
    }

    public static InfoPassLevelUpConfigRecord DeserializeInfoPassLevelUpConfigRecord(ByteBuf _buf)
    {
        return new Dota.InfoPassLevelUpConfigRecord(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public int Id { get; private set; }
    public Item.ItemInfoBean TaskComPrize { get; private set; }

    public const int __ID__ = -2022067203;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        TaskComPrize?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        TaskComPrize?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "TaskComPrize:" + TaskComPrize + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}