//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Dota
{
public sealed partial class PropPoolBean :  Bright.Config.BeanBase 
{
    public PropPoolBean(ByteBuf _buf) 
    {
        Propid = _buf.ReadInt();
        PropDes = _buf.ReadString();
        PropWeight = _buf.ReadInt();
        PropMax = _buf.ReadInt();
        PropMin = _buf.ReadInt();
        PostInit();
    }

    public static PropPoolBean DeserializePropPoolBean(ByteBuf _buf)
    {
        return new Dota.PropPoolBean(_buf);
    }

    /// <summary>
    /// 属性id
    /// </summary>
    public int Propid { get; private set; }
    /// <summary>
    /// 属性描述
    /// </summary>
    public string PropDes { get; private set; }
    /// <summary>
    /// 属性权重
    /// </summary>
    public int PropWeight { get; private set; }
    /// <summary>
    /// 属性显示最大值
    /// </summary>
    public int PropMax { get; private set; }
    /// <summary>
    /// 属性显示最小值
    /// </summary>
    public int PropMin { get; private set; }

    public const int __ID__ = 204463205;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Propid:" + Propid + ","
        + "PropDes:" + PropDes + ","
        + "PropWeight:" + PropWeight + ","
        + "PropMax:" + PropMax + ","
        + "PropMin:" + PropMin + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}