//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Dota
{
   
public partial class RoundEnemyPoolConfig
{
    private readonly Dictionary<string, Dota.RoundEnemyPoolConfigRecord> _dataMap;
    private readonly List<Dota.RoundEnemyPoolConfigRecord> _dataList;
    
    public RoundEnemyPoolConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<string, Dota.RoundEnemyPoolConfigRecord>();
        _dataList = new List<Dota.RoundEnemyPoolConfigRecord>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Dota.RoundEnemyPoolConfigRecord _v;
            _v = Dota.RoundEnemyPoolConfigRecord.DeserializeRoundEnemyPoolConfigRecord(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<string, Dota.RoundEnemyPoolConfigRecord> DataMap => _dataMap;
    public List<Dota.RoundEnemyPoolConfigRecord> DataList => _dataList;

    public Dota.RoundEnemyPoolConfigRecord GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Dota.RoundEnemyPoolConfigRecord Get(string key) => _dataMap[key];
    public Dota.RoundEnemyPoolConfigRecord this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}