//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.Conf.Dota
{
public sealed partial class UnitStarUpConfigBean :  Bright.Config.BeanBase 
{
    public UnitStarUpConfigBean(ByteBuf _buf) 
    {
        Star = _buf.ReadInt();
        AttributeBaseStrength = _buf.ReadFloat();
        AttributeBaseAgility = _buf.ReadFloat();
        AttributeBaseIntelligence = _buf.ReadFloat();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AttachWearables = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); AttachWearables.Add(_e0);}}
        PostInit();
    }

    public static UnitStarUpConfigBean DeserializeUnitStarUpConfigBean(ByteBuf _buf)
    {
        return new Dota.UnitStarUpConfigBean(_buf);
    }

    /// <summary>
    /// 星级
    /// </summary>
    public int Star { get; private set; }
    /// <summary>
    /// 基础力量
    /// </summary>
    public float AttributeBaseStrength { get; private set; }
    /// <summary>
    /// 基础敏捷
    /// </summary>
    public float AttributeBaseAgility { get; private set; }
    /// <summary>
    /// 基础智力
    /// </summary>
    public float AttributeBaseIntelligence { get; private set; }
    /// <summary>
    /// 饰品
    /// </summary>
    public System.Collections.Generic.List<string> AttachWearables { get; private set; }

    public const int __ID__ = -1335876583;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Star:" + Star + ","
        + "AttributeBaseStrength:" + AttributeBaseStrength + ","
        + "AttributeBaseAgility:" + AttributeBaseAgility + ","
        + "AttributeBaseIntelligence:" + AttributeBaseIntelligence + ","
        + "AttachWearables:" + Bright.Common.StringUtil.CollectionToString(AttachWearables) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}