//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.Conf.Dota
{
public sealed partial class UnitTalentInfoBean :  Bright.Config.BeanBase 
{
    public UnitTalentInfoBean(ByteBuf _buf) 
    {
        TalentLevel = _buf.ReadInt();
        TalentLeft = _buf.ReadString();
        TalentRight = _buf.ReadString();
        PostInit();
    }

    public static UnitTalentInfoBean DeserializeUnitTalentInfoBean(ByteBuf _buf)
    {
        return new Dota.UnitTalentInfoBean(_buf);
    }

    /// <summary>
    /// 天赋组索引
    /// </summary>
    public int TalentLevel { get; private set; }
    /// <summary>
    /// 左侧天赋
    /// </summary>
    public string TalentLeft { get; private set; }
    /// <summary>
    /// 右侧天赋
    /// </summary>
    public string TalentRight { get; private set; }

    public const int __ID__ = 1336631972;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "TalentLevel:" + TalentLevel + ","
        + "TalentLeft:" + TalentLeft + ","
        + "TalentRight:" + TalentRight + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}