//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.Conf.Dota
{
public sealed partial class WearableConfigRecord :  Bright.Config.BeanBase 
{
    public WearableConfigRecord(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        Prefab = _buf.ReadString();
        ImageInventory = _buf.ReadString();
        ItemDescription = _buf.ReadString();
        ItemName = _buf.ReadString();
        Rarity = _buf.ReadString();
        ItemRarity = _buf.ReadString();
        UsedByHeroes = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Bundle = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); Bundle.Add(_e0);}}
        PostInit();
    }

    public static WearableConfigRecord DeserializeWearableConfigRecord(ByteBuf _buf)
    {
        return new Dota.WearableConfigRecord(_buf);
    }

    /// <summary>
    /// 主键
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 类型
    /// </summary>
    public string Prefab { get; private set; }
    /// <summary>
    /// icon
    /// </summary>
    public string ImageInventory { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string ItemDescription { get; private set; }
    /// <summary>
    /// 饰品名称
    /// </summary>
    public string ItemName { get; private set; }
    /// <summary>
    /// 饰品稀有度
    /// </summary>
    public string Rarity { get; private set; }
    /// <summary>
    /// 饰品稀有度
    /// </summary>
    public string ItemRarity { get; private set; }
    /// <summary>
    /// 使用英雄
    /// </summary>
    public string UsedByHeroes { get; private set; }
    /// <summary>
    /// 礼包内道具
    /// </summary>
    public System.Collections.Generic.List<string> Bundle { get; private set; }

    public const int __ID__ = -739232222;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Prefab:" + Prefab + ","
        + "ImageInventory:" + ImageInventory + ","
        + "ItemDescription:" + ItemDescription + ","
        + "ItemName:" + ItemName + ","
        + "Rarity:" + Rarity + ","
        + "ItemRarity:" + ItemRarity + ","
        + "UsedByHeroes:" + UsedByHeroes + ","
        + "Bundle:" + Bright.Common.StringUtil.CollectionToString(Bundle) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}