//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.Conf.Title
{
public sealed partial class TitleConfigRecord :  Bright.Config.BeanBase 
{
    public TitleConfigRecord(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        TitleName = _buf.ReadString();
        TitleType = _buf.ReadInt();
        TitleValidTime = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);TitleBuffs = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TitleBuffs.Add(_e0);}}
        PostInit();
    }

    public static TitleConfigRecord DeserializeTitleConfigRecord(ByteBuf _buf)
    {
        return new Title.TitleConfigRecord(_buf);
    }

    /// <summary>
    /// 称号Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 称号名称
    /// </summary>
    public string TitleName { get; private set; }
    /// <summary>
    /// 称号类型
    /// </summary>
    public int TitleType { get; private set; }
    /// <summary>
    /// 称号有效时间
    /// </summary>
    public int TitleValidTime { get; private set; }
    /// <summary>
    /// 称号Buff
    /// </summary>
    public System.Collections.Generic.List<int> TitleBuffs { get; private set; }

    public const int __ID__ = -1819833771;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "TitleName:" + TitleName + ","
        + "TitleType:" + TitleType + ","
        + "TitleValidTime:" + TitleValidTime + ","
        + "TitleBuffs:" + Bright.Common.StringUtil.CollectionToString(TitleBuffs) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}