//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Title
{
   
public partial class TitleConfig
{
    private readonly Dictionary<int, Title.TitleConfigRecord> _dataMap;
    private readonly List<Title.TitleConfigRecord> _dataList;
    
    public TitleConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Title.TitleConfigRecord>();
        _dataList = new List<Title.TitleConfigRecord>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Title.TitleConfigRecord _v;
            _v = Title.TitleConfigRecord.DeserializeTitleConfigRecord(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Title.TitleConfigRecord> DataMap => _dataMap;
    public List<Title.TitleConfigRecord> DataList => _dataList;

    public Title.TitleConfigRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Title.TitleConfigRecord Get(int key) => _dataMap[key];
    public Title.TitleConfigRecord this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}