//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Draw
{
   
public partial class DrawTreasureConfig
{
    private readonly Dictionary<int, Draw.DrawTreasureConfigRecord> _dataMap;
    private readonly List<Draw.DrawTreasureConfigRecord> _dataList;
    
    public DrawTreasureConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Draw.DrawTreasureConfigRecord>();
        _dataList = new List<Draw.DrawTreasureConfigRecord>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Draw.DrawTreasureConfigRecord _v;
            _v = Draw.DrawTreasureConfigRecord.DeserializeDrawTreasureConfigRecord(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Draw.DrawTreasureConfigRecord> DataMap => _dataMap;
    public List<Draw.DrawTreasureConfigRecord> DataList => _dataList;

    public Draw.DrawTreasureConfigRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Draw.DrawTreasureConfigRecord Get(int key) => _dataMap[key];
    public Draw.DrawTreasureConfigRecord this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}