//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.Conf.Draw
{
public sealed partial class DrawTreasureConfigRecord :  Bright.Config.BeanBase 
{
    public DrawTreasureConfigRecord(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        CostType = _buf.ReadInt();
        RealPrice = _buf.ReadInt();
        FreeInterval = _buf.ReadInt();
        SpePrizeTimes = _buf.ReadInt();
        ComItemPoolGroup = _buf.ReadInt();
        SpeItemPoolGroup = _buf.ReadInt();
        PostInit();
    }

    public static DrawTreasureConfigRecord DeserializeDrawTreasureConfigRecord(ByteBuf _buf)
    {
        return new Draw.DrawTreasureConfigRecord(_buf);
    }

    /// <summary>
    /// 宝箱id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 货币类型
    /// </summary>
    public int CostType { get; private set; }
    /// <summary>
    /// 货币数量
    /// </summary>
    public int RealPrice { get; private set; }
    /// <summary>
    /// 免费时间间隔(s)
    /// </summary>
    public int FreeInterval { get; private set; }
    /// <summary>
    /// 干涉次数
    /// </summary>
    public int SpePrizeTimes { get; private set; }
    /// <summary>
    /// 普通奖池组
    /// </summary>
    public int ComItemPoolGroup { get; private set; }
    /// <summary>
    /// 特殊奖池组
    /// </summary>
    public int SpeItemPoolGroup { get; private set; }

    public const int __ID__ = 894096208;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "CostType:" + CostType + ","
        + "RealPrice:" + RealPrice + ","
        + "FreeInterval:" + FreeInterval + ","
        + "SpePrizeTimes:" + SpePrizeTimes + ","
        + "ComItemPoolGroup:" + ComItemPoolGroup + ","
        + "SpeItemPoolGroup:" + SpeItemPoolGroup + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}