//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.Conf.Activity
{
public sealed partial class ActivityConfigRecord :  Bright.Config.BeanBase 
{
    public ActivityConfigRecord(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        IsValid = _buf.ReadBool();
        IsCyclicActivity = _buf.ReadBool();
        ActivityName = _buf.ReadString();
        ActivityScript = _buf.ReadString();
        PostInit();
    }

    public static ActivityConfigRecord DeserializeActivityConfigRecord(ByteBuf _buf)
    {
        return new Activity.ActivityConfigRecord(_buf);
    }

    /// <summary>
    /// 活动id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 是否启用
    /// </summary>
    public bool IsValid { get; private set; }
    /// <summary>
    /// 循环活动
    /// </summary>
    public bool IsCyclicActivity { get; private set; }
    /// <summary>
    /// 活动名称
    /// </summary>
    public string ActivityName { get; private set; }
    /// <summary>
    /// 活动脚本
    /// </summary>
    public string ActivityScript { get; private set; }

    public const int __ID__ = -1751340959;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "IsValid:" + IsValid + ","
        + "IsCyclicActivity:" + IsCyclicActivity + ","
        + "ActivityName:" + ActivityName + ","
        + "ActivityScript:" + ActivityScript + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}