//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Activity
{
public sealed partial class BattlePassBean :  Bright.Config.BeanBase 
{
    public BattlePassBean(ByteBuf _buf) 
    {
        Level = _buf.ReadInt();
        Exp = _buf.ReadInt();
        ItemConfigId = _buf.ReadInt();
        ItemCount = _buf.ReadInt();
        VIPItemConfigId = _buf.ReadInt();
        VIPItemCount = _buf.ReadInt();
        PostInit();
    }

    public static BattlePassBean DeserializeBattlePassBean(ByteBuf _buf)
    {
        return new Activity.BattlePassBean(_buf);
    }

    /// <summary>
    /// 等级
    /// </summary>
    public int Level { get; private set; }
    /// <summary>
    /// 升级经验
    /// </summary>
    public int Exp { get; private set; }
    /// <summary>
    /// 道具索引
    /// </summary>
    public int ItemConfigId { get; private set; }
    /// <summary>
    /// 道具数量
    /// </summary>
    public int ItemCount { get; private set; }
    /// <summary>
    /// vip道具索引
    /// </summary>
    public int VIPItemConfigId { get; private set; }
    /// <summary>
    /// vip道具数量
    /// </summary>
    public int VIPItemCount { get; private set; }

    public const int __ID__ = -1192206088;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Level:" + Level + ","
        + "Exp:" + Exp + ","
        + "ItemConfigId:" + ItemConfigId + ","
        + "ItemCount:" + ItemCount + ","
        + "VIPItemConfigId:" + VIPItemConfigId + ","
        + "VIPItemCount:" + VIPItemCount + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}