//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.Conf.Activity
{
public sealed partial class InvestMetaStoneBean :  Bright.Config.BeanBase 
{
    public InvestMetaStoneBean(ByteBuf _buf) 
    {
        Need = _buf.ReadInt();
        GainMin = _buf.ReadInt();
        GainMax = _buf.ReadInt();
        PostInit();
    }

    public static InvestMetaStoneBean DeserializeInvestMetaStoneBean(ByteBuf _buf)
    {
        return new Activity.InvestMetaStoneBean(_buf);
    }

    /// <summary>
    /// 需要数量
    /// </summary>
    public int Need { get; private set; }
    /// <summary>
    /// 获得最小数量
    /// </summary>
    public int GainMin { get; private set; }
    /// <summary>
    /// 获得最大数量
    /// </summary>
    public int GainMax { get; private set; }

    public const int __ID__ = 525361628;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Need:" + Need + ","
        + "GainMin:" + GainMin + ","
        + "GainMax:" + GainMax + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}