//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Activity
{
   
public partial class TActivityHeroRecordLevel
{
    private readonly Dictionary<int, Activity.TActivityHeroRecordLevelRecord> _dataMap;
    private readonly List<Activity.TActivityHeroRecordLevelRecord> _dataList;
    
    public TActivityHeroRecordLevel(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Activity.TActivityHeroRecordLevelRecord>();
        _dataList = new List<Activity.TActivityHeroRecordLevelRecord>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Activity.TActivityHeroRecordLevelRecord _v;
            _v = Activity.TActivityHeroRecordLevelRecord.DeserializeTActivityHeroRecordLevelRecord(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Activity.TActivityHeroRecordLevelRecord> DataMap => _dataMap;
    public List<Activity.TActivityHeroRecordLevelRecord> DataList => _dataList;

    public Activity.TActivityHeroRecordLevelRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Activity.TActivityHeroRecordLevelRecord Get(int key) => _dataMap[key];
    public Activity.TActivityHeroRecordLevelRecord this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}