//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Activity
{
public sealed partial class TActivityGiftCommondRecord :  Bright.Config.BeanBase 
{
    public TActivityGiftCommondRecord(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        IsValid = _buf.ReadBool();
        GiftCommond = _buf.ReadString();
        GiftCount = _buf.ReadInt();
        ActivityStartTime = _buf.ReadLong();
        ActivityEndTime = _buf.ReadLong();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ItemGroup = new System.Collections.Generic.List<Item.ItemInfoBean>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Item.ItemInfoBean _e0;  _e0 = Item.ItemInfoBean.DeserializeItemInfoBean(_buf); ItemGroup.Add(_e0);}}
        PostInit();
    }

    public static TActivityGiftCommondRecord DeserializeTActivityGiftCommondRecord(ByteBuf _buf)
    {
        return new Activity.TActivityGiftCommondRecord(_buf);
    }

    /// <summary>
    /// 礼包Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 是否有效
    /// </summary>
    public bool IsValid { get; private set; }
    /// <summary>
    /// 礼包口令
    /// </summary>
    public string GiftCommond { get; private set; }
    /// <summary>
    /// 礼包数量
    /// </summary>
    public int GiftCount { get; private set; }
    /// <summary>
    /// 开启时间
    /// </summary>
    public long ActivityStartTime { get; private set; }
    public long ActivityStartTime_Millis => ActivityStartTime * 1000L;
    /// <summary>
    /// 结束时间
    /// </summary>
    public long ActivityEndTime { get; private set; }
    public long ActivityEndTime_Millis => ActivityEndTime * 1000L;
    public System.Collections.Generic.List<Item.ItemInfoBean> ItemGroup { get; private set; }

    public const int __ID__ = 368169750;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in ItemGroup) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in ItemGroup) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "IsValid:" + IsValid + ","
        + "GiftCommond:" + GiftCommond + ","
        + "GiftCount:" + GiftCount + ","
        + "ActivityStartTime:" + ActivityStartTime + ","
        + "ActivityEndTime:" + ActivityEndTime + ","
        + "ItemGroup:" + Bright.Common.StringUtil.CollectionToString(ItemGroup) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}