//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.Conf.Item
{
   
public partial class ItemPrizePoolConfig
{
    private readonly Dictionary<int, Item.ItemPrizePoolConfigRecord> _dataMap;
    private readonly List<Item.ItemPrizePoolConfigRecord> _dataList;
    
    public ItemPrizePoolConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Item.ItemPrizePoolConfigRecord>();
        _dataList = new List<Item.ItemPrizePoolConfigRecord>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Item.ItemPrizePoolConfigRecord _v;
            _v = Item.ItemPrizePoolConfigRecord.DeserializeItemPrizePoolConfigRecord(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Item.ItemPrizePoolConfigRecord> DataMap => _dataMap;
    public List<Item.ItemPrizePoolConfigRecord> DataList => _dataList;

    public Item.ItemPrizePoolConfigRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Item.ItemPrizePoolConfigRecord Get(int key) => _dataMap[key];
    public Item.ItemPrizePoolConfigRecord this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}