//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Item
{
   
public partial class ItemEquipConfig
{
    private readonly Dictionary<int, Item.ItemEquipConfigRecord> _dataMap;
    private readonly List<Item.ItemEquipConfigRecord> _dataList;
    
    public ItemEquipConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Item.ItemEquipConfigRecord>();
        _dataList = new List<Item.ItemEquipConfigRecord>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Item.ItemEquipConfigRecord _v;
            _v = Item.ItemEquipConfigRecord.DeserializeItemEquipConfigRecord(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Item.ItemEquipConfigRecord> DataMap => _dataMap;
    public List<Item.ItemEquipConfigRecord> DataList => _dataList;

    public Item.ItemEquipConfigRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Item.ItemEquipConfigRecord Get(int key) => _dataMap[key];
    public Item.ItemEquipConfigRecord this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}