//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Item
{
public sealed partial class ItemEquipConfigRecord :  Bright.Config.BeanBase 
{
    public ItemEquipConfigRecord(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        EquipSlot = (EEnum.EEquipSolt)_buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);EquipRandomProp = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); EquipRandomProp.Add(_e0);}}
        SuitId = _buf.ReadInt();
        SuitName = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);SuitInfo = new System.Collections.Generic.List<Item.ItemEquipSuitBean>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Item.ItemEquipSuitBean _e0;  _e0 = Item.ItemEquipSuitBean.DeserializeItemEquipSuitBean(_buf); SuitInfo.Add(_e0);}}
        PostInit();
    }

    public static ItemEquipConfigRecord DeserializeItemEquipConfigRecord(ByteBuf _buf)
    {
        return new Item.ItemEquipConfigRecord(_buf);
    }

    /// <summary>
    /// 装备id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 穿戴部位
    /// </summary>
    public EEnum.EEquipSolt EquipSlot { get; private set; }
    /// <summary>
    /// 装备随机属性
    /// </summary>
    public System.Collections.Generic.List<int> EquipRandomProp { get; private set; }
    /// <summary>
    /// 套装Id
    /// </summary>
    public int SuitId { get; private set; }
    /// <summary>
    /// 套装名称
    /// </summary>
    public string SuitName { get; private set; }
    public System.Collections.Generic.List<Item.ItemEquipSuitBean> SuitInfo { get; private set; }

    public const int __ID__ = 1892209429;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in SuitInfo) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in SuitInfo) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "EquipSlot:" + EquipSlot + ","
        + "EquipRandomProp:" + Bright.Common.StringUtil.CollectionToString(EquipRandomProp) + ","
        + "SuitId:" + SuitId + ","
        + "SuitName:" + SuitName + ","
        + "SuitInfo:" + Bright.Common.StringUtil.CollectionToString(SuitInfo) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}