//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Item
{
public sealed partial class ItemEquipSuitBean :  Bright.Config.BeanBase 
{
    public ItemEquipSuitBean(ByteBuf _buf) 
    {
        SuitCount = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);SuitBuffs = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); SuitBuffs.Add(_e0);}}
        PostInit();
    }

    public static ItemEquipSuitBean DeserializeItemEquipSuitBean(ByteBuf _buf)
    {
        return new Item.ItemEquipSuitBean(_buf);
    }

    /// <summary>
    /// 套装数量
    /// </summary>
    public int SuitCount { get; private set; }
    /// <summary>
    /// 套装Buff效果
    /// </summary>
    public System.Collections.Generic.List<int> SuitBuffs { get; private set; }

    public const int __ID__ = -1915750849;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "SuitCount:" + SuitCount + ","
        + "SuitBuffs:" + Bright.Common.StringUtil.CollectionToString(SuitBuffs) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}