//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Item
{
public sealed partial class ItemRandomCountBean :  Bright.Config.BeanBase 
{
    public ItemRandomCountBean(ByteBuf _buf) 
    {
        RandomCount = _buf.ReadInt();
        RandomWeight = _buf.ReadInt();
        PostInit();
    }

    public static ItemRandomCountBean DeserializeItemRandomCountBean(ByteBuf _buf)
    {
        return new Item.ItemRandomCountBean(_buf);
    }

    /// <summary>
    /// 随机数量
    /// </summary>
    public int RandomCount { get; private set; }
    /// <summary>
    /// 随机权重
    /// </summary>
    public int RandomWeight { get; private set; }

    public const int __ID__ = 1428199662;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "RandomCount:" + RandomCount + ","
        + "RandomWeight:" + RandomWeight + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}