//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.Conf.Item
{
   
public partial class ItemBuffConfig
{
    private readonly Dictionary<int, Item.ItemBuffConfigRecord> _dataMap;
    private readonly List<Item.ItemBuffConfigRecord> _dataList;
    
    public ItemBuffConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Item.ItemBuffConfigRecord>();
        _dataList = new List<Item.ItemBuffConfigRecord>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Item.ItemBuffConfigRecord _v;
            _v = Item.ItemBuffConfigRecord.DeserializeItemBuffConfigRecord(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Item.ItemBuffConfigRecord> DataMap => _dataMap;
    public List<Item.ItemBuffConfigRecord> DataList => _dataList;

    public Item.ItemBuffConfigRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Item.ItemBuffConfigRecord Get(int key) => _dataMap[key];
    public Item.ItemBuffConfigRecord this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}