//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.Conf.Item
{
public sealed partial class ItemPoolGroupBean :  Bright.Config.BeanBase 
{
    public ItemPoolGroupBean(ByteBuf _buf) 
    {
        ItemPoolConfigId = _buf.ReadInt();
        ItemPoolWeight = _buf.ReadInt();
        PostInit();
    }

    public static ItemPoolGroupBean DeserializeItemPoolGroupBean(ByteBuf _buf)
    {
        return new Item.ItemPoolGroupBean(_buf);
    }

    /// <summary>
    /// 池子索引
    /// </summary>
    public int ItemPoolConfigId { get; private set; }
    /// <summary>
    /// 池子权重
    /// </summary>
    public int ItemPoolWeight { get; private set; }

    public const int __ID__ = -910613595;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ItemPoolConfigId:" + ItemPoolConfigId + ","
        + "ItemPoolWeight:" + ItemPoolWeight + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}