//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.Conf.Item
{
public sealed partial class ItemPrizePoolGroupConfigRecord :  Bright.Config.BeanBase 
{
    public ItemPrizePoolGroupConfigRecord(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        IsRandomRepeat = _buf.ReadBool();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);RandomCountInfo = new System.Collections.Generic.List<Item.ItemRandomCountBean>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Item.ItemRandomCountBean _e0;  _e0 = Item.ItemRandomCountBean.DeserializeItemRandomCountBean(_buf); RandomCountInfo.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ItemPoolGroup = new System.Collections.Generic.List<Item.ItemPoolGroupBean>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Item.ItemPoolGroupBean _e0;  _e0 = Item.ItemPoolGroupBean.DeserializeItemPoolGroupBean(_buf); ItemPoolGroup.Add(_e0);}}
        PostInit();
    }

    public static ItemPrizePoolGroupConfigRecord DeserializeItemPrizePoolGroupConfigRecord(ByteBuf _buf)
    {
        return new Item.ItemPrizePoolGroupConfigRecord(_buf);
    }

    /// <summary>
    /// 池子组id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 随机奖励是否重复
    /// </summary>
    public bool IsRandomRepeat { get; private set; }
    public System.Collections.Generic.List<Item.ItemRandomCountBean> RandomCountInfo { get; private set; }
    public System.Collections.Generic.List<Item.ItemPoolGroupBean> ItemPoolGroup { get; private set; }

    public const int __ID__ = -486667182;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in RandomCountInfo) { _e?.Resolve(_tables); }
        foreach(var _e in ItemPoolGroup) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in RandomCountInfo) { _e?.TranslateText(translator); }
        foreach(var _e in ItemPoolGroup) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "IsRandomRepeat:" + IsRandomRepeat + ","
        + "RandomCountInfo:" + Bright.Common.StringUtil.CollectionToString(RandomCountInfo) + ","
        + "ItemPoolGroup:" + Bright.Common.StringUtil.CollectionToString(ItemPoolGroup) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}