//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.Conf.Item
{
public sealed partial class ItemInfoWithIndexBean :  Bright.Config.BeanBase 
{
    public ItemInfoWithIndexBean(ByteBuf _buf) 
    {
        Index = _buf.ReadInt();
        ItemConfigId = _buf.ReadInt();
        ItemCount = _buf.ReadInt();
        PostInit();
    }

    public static ItemInfoWithIndexBean DeserializeItemInfoWithIndexBean(ByteBuf _buf)
    {
        return new Item.ItemInfoWithIndexBean(_buf);
    }

    /// <summary>
    /// 道具组索引
    /// </summary>
    public int Index { get; private set; }
    /// <summary>
    /// 道具索引
    /// </summary>
    public int ItemConfigId { get; private set; }
    /// <summary>
    /// 道具数量
    /// </summary>
    public int ItemCount { get; private set; }

    public const int __ID__ = -591448064;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Index:" + Index + ","
        + "ItemConfigId:" + ItemConfigId + ","
        + "ItemCount:" + ItemCount + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}