//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Item
{
public sealed partial class ItemBuffConfigRecord :  Bright.Config.BeanBase 
{
    public ItemBuffConfigRecord(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        BuffName = _buf.ReadString();
        BuffValidTime = _buf.ReadInt();
        BuffTargetType = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BuffTargetArgs = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); BuffTargetArgs.Add(_e0);}}
        BuffQuality = _buf.ReadInt();
        BuffGroupPriority = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BuffGroupMember = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); BuffGroupMember.Add(_e0);}}
        PostInit();
    }

    public static ItemBuffConfigRecord DeserializeItemBuffConfigRecord(ByteBuf _buf)
    {
        return new Item.ItemBuffConfigRecord(_buf);
    }

    /// <summary>
    /// Buffid
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// Buff名称
    /// </summary>
    public string BuffName { get; private set; }
    /// <summary>
    /// buff有效时间(秒)
    /// </summary>
    public int BuffValidTime { get; private set; }
    /// <summary>
    /// 目标类型
    /// </summary>
    public string BuffTargetType { get; private set; }
    /// <summary>
    /// 目标类型参数
    /// </summary>
    public System.Collections.Generic.List<int> BuffTargetArgs { get; private set; }
    /// <summary>
    /// Buff品质
    /// </summary>
    public int BuffQuality { get; private set; }
    /// <summary>
    /// Buff组内优先级
    /// </summary>
    public int BuffGroupPriority { get; private set; }
    /// <summary>
    /// 同组Buff成员
    /// </summary>
    public System.Collections.Generic.List<int> BuffGroupMember { get; private set; }

    public const int __ID__ = 692964180;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "BuffName:" + BuffName + ","
        + "BuffValidTime:" + BuffValidTime + ","
        + "BuffTargetType:" + BuffTargetType + ","
        + "BuffTargetArgs:" + Bright.Common.StringUtil.CollectionToString(BuffTargetArgs) + ","
        + "BuffQuality:" + BuffQuality + ","
        + "BuffGroupPriority:" + BuffGroupPriority + ","
        + "BuffGroupMember:" + Bright.Common.StringUtil.CollectionToString(BuffGroupMember) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}