//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.Conf.Shop
{
public sealed partial class ShopSellItemBean :  Bright.Config.BeanBase 
{
    public ShopSellItemBean(ByteBuf _buf) 
    {
        SellConfigid = _buf.ReadInt();
        Selllabel = _buf.ReadString();
        SellCount = _buf.ReadInt();
        SellRefreshType = (EEnum.ESellRefreshType)_buf.ReadInt();
        SellStartTime = _buf.ReadInt();
        SellValidTime = _buf.ReadInt();
        ItemConfigId = _buf.ReadInt();
        ItemName = _buf.ReadString();
        ItemCount = _buf.ReadInt();
        CostType = (EEnum.EMoneyType)_buf.ReadInt();
        OriginPrice = _buf.ReadInt();
        RealPrice = _buf.ReadInt();
        OverSeaOriginPrice = _buf.ReadInt();
        OverSeaRealPrice = _buf.ReadInt();
        Discount = _buf.ReadInt();
        VipLimit = _buf.ReadBool();
        IsVaild = _buf.ReadBool();
        PostInit();
    }

    public static ShopSellItemBean DeserializeShopSellItemBean(ByteBuf _buf)
    {
        return new Shop.ShopSellItemBean(_buf);
    }

    /// <summary>
    /// 售卖索引
    /// </summary>
    public int SellConfigid { get; private set; }
    /// <summary>
    /// 售卖标签
    /// </summary>
    public string Selllabel { get; private set; }
    /// <summary>
    /// 售卖数量
    /// </summary>
    public int SellCount { get; private set; }
    /// <summary>
    /// 商品刷新类型
    /// </summary>
    public EEnum.ESellRefreshType SellRefreshType { get; private set; }
    /// <summary>
    /// 商品开启时间
    /// </summary>
    public int SellStartTime { get; private set; }
    /// <summary>
    /// 商品有效时间
    /// </summary>
    public int SellValidTime { get; private set; }
    /// <summary>
    /// 道具索引
    /// </summary>
    public int ItemConfigId { get; private set; }
    /// <summary>
    /// 道具名称
    /// </summary>
    public string ItemName { get; private set; }
    /// <summary>
    /// 道具数量
    /// </summary>
    public int ItemCount { get; private set; }
    /// <summary>
    /// 货币类型
    /// </summary>
    public EEnum.EMoneyType CostType { get; private set; }
    /// <summary>
    /// 初始价格
    /// </summary>
    public int OriginPrice { get; private set; }
    /// <summary>
    /// 最终价格
    /// </summary>
    public int RealPrice { get; private set; }
    /// <summary>
    /// 海外初始价格
    /// </summary>
    public int OverSeaOriginPrice { get; private set; }
    /// <summary>
    /// 海外最终价格
    /// </summary>
    public int OverSeaRealPrice { get; private set; }
    /// <summary>
    /// 折扣
    /// </summary>
    public int Discount { get; private set; }
    /// <summary>
    /// Vip限制
    /// </summary>
    public bool VipLimit { get; private set; }
    /// <summary>
    /// 是否启用
    /// </summary>
    public bool IsVaild { get; private set; }

    public const int __ID__ = -383084317;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "SellConfigid:" + SellConfigid + ","
        + "Selllabel:" + Selllabel + ","
        + "SellCount:" + SellCount + ","
        + "SellRefreshType:" + SellRefreshType + ","
        + "SellStartTime:" + SellStartTime + ","
        + "SellValidTime:" + SellValidTime + ","
        + "ItemConfigId:" + ItemConfigId + ","
        + "ItemName:" + ItemName + ","
        + "ItemCount:" + ItemCount + ","
        + "CostType:" + CostType + ","
        + "OriginPrice:" + OriginPrice + ","
        + "RealPrice:" + RealPrice + ","
        + "OverSeaOriginPrice:" + OverSeaOriginPrice + ","
        + "OverSeaRealPrice:" + OverSeaRealPrice + ","
        + "Discount:" + Discount + ","
        + "VipLimit:" + VipLimit + ","
        + "IsVaild:" + IsVaild + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}