//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Achievement
{
   
public partial class AchievementConfig
{
    private readonly Dictionary<int, Achievement.AchievementConfigRecord> _dataMap;
    private readonly List<Achievement.AchievementConfigRecord> _dataList;
    
    public AchievementConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Achievement.AchievementConfigRecord>();
        _dataList = new List<Achievement.AchievementConfigRecord>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Achievement.AchievementConfigRecord _v;
            _v = Achievement.AchievementConfigRecord.DeserializeAchievementConfigRecord(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Achievement.AchievementConfigRecord> DataMap => _dataMap;
    public List<Achievement.AchievementConfigRecord> DataList => _dataList;

    public Achievement.AchievementConfigRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Achievement.AchievementConfigRecord Get(int key) => _dataMap[key];
    public Achievement.AchievementConfigRecord this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}