//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.Conf.EEnum
{ 
    public enum EActivityType
    {
        /// <summary>
        /// 7日登录
        /// </summary>
        TActivitySevenDayLogin = 1,
        /// <summary>
        /// 每月登录
        /// </summary>
        TActivityMonthLogin = 2,
        /// <summary>
        /// 战令
        /// </summary>
        TActivityBattlePass = 3,
        /// <summary>
        /// 月卡
        /// </summary>
        TActivityMemberShip = 4,
        /// <summary>
        /// 英雄等级
        /// </summary>
        TActivityHeroRecordLevel = 5,
        /// <summary>
        /// 每日奖励
        /// </summary>
        TActivityDailyOnlinePrize = 6,
        /// <summary>
        /// 原石骰子
        /// </summary>
        TActivityInvestMetaStone = 7,
        TActivityTotalGainMetaStone = 8,
        TActivityTotalOnlineTime = 9,
        TActivityTotalSpendMetaStone = 10,
        /// <summary>
        /// 兑换码
        /// </summary>
        TActivityGiftCommond = 11,
        TActivityMentorshipTree = 12,
        ServerZoneActivityMax = 1000,
    }

} 
