//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.Conf.EEnum
{ 
    public enum EBagSlotType
    {
        /// <summary>
        /// 允许叠加
        /// </summary>
        AllowMany = 0,
        /// <summary>
        /// 禁止叠加
        /// </summary>
        ForbidMany = 1,
        /// <summary>
        /// 不占格子
        /// </summary>
        NoSlot = 2,
    }

} 
