//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.EEnum
{ 
    public enum EEnemyCreateType
    {
        /// <summary>
        /// 默认创建
        /// </summary>
        None = 0,
        /// <summary>
        /// 召唤的战斗怪
        /// </summary>
        SummedBattle = 1,
        /// <summary>
        /// 召唤的偷蛋怪
        /// </summary>
        SummedEgg = 2,
        /// <summary>
        /// 随机替换怪
        /// </summary>
        RandomReplace = 3,
        /// <summary>
        /// 数据绑定匹配敌人
        /// </summary>
        DataDriver = 4,
        /// <summary>
        /// 共同的敌人
        /// </summary>
        PublicEnemy = 5,
    }

} 
