//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.EEnum
{ 
    public enum EEquipSolt
    {
        /// <summary>
        /// 空值
        /// </summary>
        None = 0,
        /// <summary>
        /// 神杖
        /// </summary>
        Scepter = 1,
        /// <summary>
        /// 皮肤
        /// </summary>
        Skin = 2,
        /// <summary>
        /// A类型1槽位
        /// </summary>
        InscriptionA_1 = 10,
        /// <summary>
        /// A类型2槽位
        /// </summary>
        InscriptionA_2 = 11,
        /// <summary>
        /// A类型3槽位
        /// </summary>
        InscriptionA_3 = 12,
        /// <summary>
        /// A类型4槽位
        /// </summary>
        InscriptionA_4 = 13,
        /// <summary>
        /// A类型5槽位
        /// </summary>
        InscriptionA_5 = 14,
        /// <summary>
        /// B类型1槽位
        /// </summary>
        InscriptionB_1 = 15,
        /// <summary>
        /// B类型2槽位
        /// </summary>
        InscriptionB_2 = 16,
        /// <summary>
        /// B类型3槽位
        /// </summary>
        InscriptionB_3 = 17,
        /// <summary>
        /// B类型4槽位
        /// </summary>
        InscriptionB_4 = 18,
        /// <summary>
        /// B类型5槽位
        /// </summary>
        InscriptionB_5 = 19,
        /// <summary>
        /// C类型1槽位
        /// </summary>
        InscriptionC_1 = 20,
        /// <summary>
        /// C类型2槽位
        /// </summary>
        InscriptionC_2 = 21,
        /// <summary>
        /// C类型3槽位
        /// </summary>
        InscriptionC_3 = 22,
        /// <summary>
        /// C类型4槽位
        /// </summary>
        InscriptionC_4 = 23,
        /// <summary>
        /// C类型5槽位
        /// </summary>
        InscriptionC_5 = 24,
        /// <summary>
        /// 最大值
        /// </summary>
        SlotMax = 30,
    }

} 
