//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.EEnum
{ 
    public enum EItemUseScript
    {
        /// <summary>
        /// 空值
        /// </summary>
        None = 0,
        /// <summary>
        /// 获取奖励
        /// </summary>
        GetPrize = 1,
        /// <summary>
        /// 穿戴
        /// </summary>
        DressUp = 2,
        /// <summary>
        /// 祝福Buff
        /// </summary>
        AddBuff = 3,
        /// <summary>
        /// 消耗数量
        /// </summary>
        CostCount = 4,
    }

} 
