//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.Conf.EEnum
{ 
    public enum EItemType
    {
        /// <summary>
        /// 道具
        /// </summary>
        None = 0,
        /// <summary>
        /// 装备
        /// </summary>
        Equip = 1,
        /// <summary>
        /// 礼包
        /// </summary>
        Treasure = 2,
        /// <summary>
        /// 限时道具
        /// </summary>
        TimeItem = 3,
        /// <summary>
        /// 信使
        /// </summary>
        Courier = 4,
        /// <summary>
        /// 祝福
        /// </summary>
        Buff = 5,
        /// <summary>
        /// 铭文
        /// </summary>
        MingWen = 6,
        /// <summary>
        /// 皮肤
        /// </summary>
        Skin = 7,
        /// <summary>
        /// 英雄经验
        /// </summary>
        HeroExp = 8,
    }

} 
