//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.EEnum
{ 
    public enum EItemAwakeScript
    {
        /// <summary>
        /// 空值
        /// </summary>
        None = 0,
        /// <summary>
        /// 添加英雄经验
        /// </summary>
        AddHeroExp = 1,
        /// <summary>
        /// 添加称号
        /// </summary>
        AddTitle = 2,
        /// <summary>
        /// 穿戴装备
        /// </summary>
        BindEquip = 3,
        /// <summary>
        /// 激活信使
        /// </summary>
        ActiveCourier = 4,
        /// <summary>
        /// 激活皮肤
        /// </summary>
        ActiveSkin = 5,
    }

} 
