//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.Conf.EEnum
{ 
    public enum EMoneyType
    {
        /// <summary>
        /// 空值
        /// </summary>
        None = 0,
        /// <summary>
        /// 金币
        /// </summary>
        Gold = 1,
        /// <summary>
        /// 木材
        /// </summary>
        Wood = 2,
        /// <summary>
        /// 魂晶
        /// </summary>
        SoulCrystal = 3,
        /// <summary>
        /// 人口
        /// </summary>
        Population = 4,
        /// <summary>
        /// 原石
        /// </summary>
        MetaStone = 101,
        /// <summary>
        /// 星石
        /// </summary>
        StarStone = 102,
        /// <summary>
        /// 钱
        /// </summary>
        Money = 103,
        /// <summary>
        /// 通用英雄经验
        /// </summary>
        ComHeroExp = 104,
        /// <summary>
        /// 铭文碎片
        /// </summary>
        MingWenExp = 105,
        /// <summary>
        /// 天梯积分
        /// </summary>
        BattleScore = 106,
    }

} 
