//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.Conf.EEnum
{ 
    public enum ERarity
    {
        /// <summary>
        /// 空值
        /// </summary>
        None = 0,
        /// <summary>
        /// 稀有度D
        /// </summary>
        D = 1,
        /// <summary>
        /// 稀有度C
        /// </summary>
        C = 2,
        /// <summary>
        /// 稀有度B
        /// </summary>
        B = 3,
        /// <summary>
        /// 稀有度A
        /// </summary>
        A = 4,
        /// <summary>
        /// 稀有度R
        /// </summary>
        R = 5,
        /// <summary>
        /// 稀有度S
        /// </summary>
        S = 10,
        /// <summary>
        /// 稀有度SS
        /// </summary>
        SS = 11,
        /// <summary>
        /// 稀有度SSR
        /// </summary>
        SSR = 12,
    }

} 
