//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.EEnum
{ 
    public enum ESellRefreshType
    {
        /// <summary>
        /// 不刷新
        /// </summary>
        None = 0,
        /// <summary>
        /// 每天
        /// </summary>
        EveryDay = 1,
        /// <summary>
        /// 每周
        /// </summary>
        EveryWeek = 2,
        /// <summary>
        /// 每月
        /// </summary>
        EveryMonth = 3,
        /// <summary>
        /// 每年
        /// </summary>
        EveryYear = 4,
        /// <summary>
        /// 每小时
        /// </summary>
        EveryHour = 5,
        /// <summary>
        /// 每赛季
        /// </summary>
        EverySeason = 6,
    }

} 
