//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.EEnum
{ 
    public enum EShopPriceType
    {
        /// <summary>
        /// 国内价格
        /// </summary>
        ChinaPrice = 0,
        /// <summary>
        /// 海外价格
        /// </summary>
        OverSeaPrice = 1,
    }

} 
